apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ethauto
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv-ethauto"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-ethauto
  namespace: prod-ethauto
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi