apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: prod-ethauto
spec:
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: pv-claim-ethauto
  containers:
  - name: python-app-ethauto
    image: 553149402753.dkr.ecr.ap-northeast-2.amazonaws.com/ecr-k3spod-prod-ethauto
    volumeMounts:
    - mountPath: "/home/output"
      name: task-pv-storage
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-credential
          key: aws-access-key
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-credential
          key: aws-secret-access-key
    - name: AWS_DEFAULT_REGION
      valueFrom:
        secretKeyRef:
          name: aws-credential
          key: aws-default-region
    command: ["sh", "/home/run.sh"]
  imagePullSecrets:
  - name: regcred