apiVersion: v1
kind: Pod
metadata:
  name: test-pod-ethauto
  namespace: test  # 수정: 테스트 네임스페이스로 변경
spec:
  containers:
    - name: test-container-ethauto
      image: 553149402753.dkr.ecr.ap-northeast-2.amazonaws.com/test-image:ethauto.v.1.3  # 수정: 테스트 이미지로 변경
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credential
              key: aws-access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credential
              key: aws-secret-access-key
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-credential
              key: aws-default-region
  imagePullSecrets:
    - name: regcred
  nodeSelector:
    node: worker01   #select deploy node
